"""Mission-sync capability requirements."""

from __future__ import annotations


MISSION_COMMAND_CAPABILITIES: dict[str, str] = {
    "mission.join": "mission.join",
    "mission.leave": "mission.leave",
    "mission.events.list": "mission.audit.read",
    "mission.message.send": "mission.message.send",
    "topic.list": "topic.read",
    "topic.create": "topic.create",
    "topic.patch": "topic.write",
    "topic.delete": "topic.delete",
    "topic.subscribe": "topic.subscribe",
    "mission.marker.list": "mission.content.read",
    "mission.marker.create": "mission.content.write",
    "mission.marker.position.patch": "mission.content.write",
    "mission.zone.list": "mission.zone.read",
    "mission.zone.create": "mission.zone.write",
    "mission.zone.patch": "mission.zone.write",
    "mission.zone.delete": "mission.zone.delete",
    "mission.registry.mission.upsert": "mission.registry.mission.write",
    "mission.registry.mission.get": "mission.registry.mission.read",
    "mission.registry.mission.list": "mission.registry.mission.read",
    "mission.registry.mission.patch": "mission.registry.mission.write",
    "mission.registry.mission.delete": "mission.registry.mission.write",
    "mission.registry.mission.parent.set": "mission.registry.mission.write",
    "mission.registry.mission_change.upsert": "mission.registry.log.write",
    "mission.registry.mission_change.list": "mission.registry.log.read",
    "mission.registry.log_entry.upsert": "mission.registry.log.write",
    "mission.registry.log_entry.list": "mission.registry.log.read",
    "mission.registry.team.upsert": "mission.registry.team.write",
    "mission.registry.team.get": "mission.registry.team.read",
    "mission.registry.team.list": "mission.registry.team.read",
    "mission.registry.team.delete": "mission.registry.team.write",
    "mission.registry.team.mission.link": "mission.registry.team.write",
    "mission.registry.team.mission.unlink": "mission.registry.team.write",
    "mission.registry.mission.zone.link": "mission.zone.write",
    "mission.registry.mission.zone.unlink": "mission.zone.write",
    "mission.registry.mission.rde.set": "mission.registry.mission.write",
    "mission.registry.team_member.upsert": "mission.registry.team.write",
    "mission.registry.team_member.get": "mission.registry.team.read",
    "mission.registry.team_member.list": "mission.registry.team.read",
    "mission.registry.team_member.delete": "mission.registry.team.write",
    "mission.registry.team_member.client.link": "mission.registry.team.write",
    "mission.registry.team_member.client.unlink": "mission.registry.team.write",
    "mission.registry.asset.upsert": "mission.registry.asset.write",
    "mission.registry.asset.get": "mission.registry.asset.read",
    "mission.registry.asset.list": "mission.registry.asset.read",
    "mission.registry.asset.delete": "mission.registry.asset.write",
    "mission.registry.skill.upsert": "mission.registry.skill.write",
    "mission.registry.skill.list": "mission.registry.skill.read",
    "mission.registry.team_member_skill.upsert": "mission.registry.skill.write",
    "mission.registry.team_member_skill.list": "mission.registry.skill.read",
    "mission.registry.task_skill_requirement.upsert": "mission.registry.skill.write",
    "mission.registry.task_skill_requirement.list": "mission.registry.skill.read",
    "mission.registry.assignment.upsert": "mission.registry.assignment.write",
    "mission.registry.assignment.list": "mission.registry.assignment.read",
    "mission.registry.assignment.asset.set": "mission.registry.assignment.write",
    "mission.registry.assignment.asset.link": "mission.registry.assignment.write",
    "mission.registry.assignment.asset.unlink": "mission.registry.assignment.write",
}
