export const endpoints = {
  status: "/Status",
  events: "/Events",
  topics: "/Topic",
  subscribers: "/Subscriber",
  subscribersAdd: "/Subscriber/Add",
  telemetry: "/Telemetry",
  files: "/File",
  images: "/Image",
  chatMessages: "/Chat/Messages",
  chatMessage: "/Chat/Message",
  chatAttachment: "/Chat/Attachment",
  clients: "/Client",
  identities: "/Identities",
  config: "/Config",
  configValidate: "/Config/Validate",
  configRollback: "/Config/Rollback",
  markers: "/api/markers",
  help: "/Help",
  examples: "/Examples",
  command: "/Command",
  appInfo: "/api/v1/app/info",
  rth: "/RTH"
};
