from .sensor_enum import *
from .location import Location
from .time import Time
from .magnetic_field import MagneticField
from .generic import (
    Acceleration,
    AmbientLight,
    AngularVelocity,
    Battery,
    ConnectionMap,
    Custom,
    Fuel,
    Gravity,
    Humidity,
    Information,
    LXMFPropagation,
    NonVolatileMemory,
    PhysicalLink,
    PowerConsumption,
    PowerProduction,
    Pressure,
    Processor,
    Proximity,
    RandomAccessMemory,
    Received,
    RNSTransport,
    Tank,
    Temperature,
)

sid_mapping = {
    SID_TIME: Time,
    SID_LOCATION: Location,
    SID_PRESSURE: Pressure,
    SID_BATTERY: Battery,
    SID_PHYSICAL_LINK: PhysicalLink,
    SID_ACCELERATION: Acceleration,
    SID_TEMPERATURE: Temperature,
    SID_HUMIDITY: Humidity,
    SID_MAGNETIC_FIELD: MagneticField,
    SID_AMBIENT_LIGHT: AmbientLight,
    SID_GRAVITY: Gravity,
    SID_ANGULAR_VELOCITY: AngularVelocity,
    SID_PROXIMITY: Proximity,
    SID_INFORMATION: Information,
    SID_RECEIVED: Received,
    SID_POWER_CONSUMPTION: PowerConsumption,
    SID_POWER_PRODUCTION: PowerProduction,
    SID_PROCESSOR: Processor,
    SID_RAM: RandomAccessMemory,
    SID_NVM: NonVolatileMemory,
    SID_TANK: Tank,
    SID_FUEL: Fuel,
    SID_LXMF_PROPAGATION: LXMFPropagation,
    SID_RNS_TRANSPORT: RNSTransport,
    SID_CONNECTION_MAP: ConnectionMap,
    SID_CUSTOM: Custom,
}
