[package]
name = "r3akt-transport-rns"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
lxmf = { package = "lxmf-wire", git = "https://github.com/FreeTAKTeam/LXMF-rs.git", rev = "fb5c2a1f938a7aab2f68e67976ef4e074218f258", version = "0.13.0", default-features = false, features = ["std"] }
lxmf-sdk = { git = "https://github.com/FreeTAKTeam/LXMF-rs.git", rev = "fb5c2a1f938a7aab2f68e67976ef4e074218f258", version = "0.13.0", default-features = false, features = ["zmq-pipeline-backend"] }
r3akt-protocol.workspace = true
rns-rpc = { package = "reticulum-rs-rpc", git = "https://github.com/FreeTAKTeam/LXMF-rs.git", rev = "fb5c2a1f938a7aab2f68e67976ef4e074218f258", version = "0.13.0" }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeromq.workspace = true

[dev-dependencies]

[lints]
workspace = true
